#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/app/id1234793120
playstore_link                            : https://play.google.com/store/apps/details?id=com.example.okul
# presskit_download_link                    : https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  :  assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :  Okul                                         # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Fast & Simple English-Persian-Turkish Dictionary – Quick, Easy, and Always at Your Fingertips!.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Nabi Rahmani                                
# your_link                                 : https://emilbaehr.com                     
your_city                                 : Istanbul                                
email_address                             : nabi007.dev@gmail.com
# facebook_username                         :                                           
# instagram_username                        : ebaehr
twitter_username                          : nabirahmani_dev
github_username                           : Nabi-Rahmani
# youtube_username                          :
# mastodon_link                             : https://mastodon.social/@ebaehr



# Feature List                            Edit, add or remove features to be presented.
features                                  :
  - title                                 : Favorites
    description                           : Users can favorite/unfavorite words, managed with Riverpod and Hive.
    fontawesome_icon_name                 : heart

  - title                                 : History
    description                           : Recently searched words are saved for easy access.
    fontawesome_icon_name                 : history

  - title                                 : Word of the Day (WOD)
    description                           : A dedicated tab for the Word of the Day. Functionality is still in progress.
    fontawesome_icon_name                 : calendar-alt

  - title                                 : Dark/Light Mode
    description                           : Users can switch between themes.
    fontawesome_icon_name                 : adjust

  - title                                 : Multi-Language Support
    description                           : Supports English Persian Turkish, with text-to-speech using FlutterTts.
    fontawesome_icon_name                 : language

  - title                                 : Search Functionality
    description                           : Users can search for words from a JSON database. Works well on the simulator but had issues on a physical device (debugged).
    fontawesome_icon_name                 : search




# Theme Settings
topbar_color                              : "#d53953"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1c63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#e6e6e6"
social_icons_background_color             : "#1d63ea"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
